### ISSUE TITLE
The type or namespace 'FixedBuffer' could not be found.

### ISSUE THREAD

**Issue by Pepperized** [HouraiTeahouse/Backroll#1]
Can't seem to resolve a missing package or file.
I have tried:

- Performing 'git pull' on each HouraiTeahouse repo.
- Deleting "Temp" and "Library" in Unity project root and restarting my PC.
- Restoring NuGet packages.

BackrollConnection.cs
Line 600 causing the build error.

Other lines with errors within file:

- 157 (directly related)
- 218
- 225 (related to FixedBuffer)

**Comment by james7132** [comment]
I strongly suggest using the Unity Package Manager version to fetch the dependencies. It should resolve any version mismatches that occur. This is likely occurring because you are pulling the HEAD of HouraiNetworking, HouraiCore, and Backroll, which may not be synchronized. I recently replaced FixedBuffer in HouraiCore with the standard System.(ReadOnly)Span<byte>, and had not updated Backroll to use it yet.

a77a996 should fix this if you are pulling from HEAD, but you will likely need to pull the updated dependencies via the Package Manager.
